baseURL = "https://maglers.netlify.com"
DefaultContentLanguage = "pl"
disableLanguages = ["en"]
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "MAGLES | Magnetic Levitation Systems"

[Languages.pl]
contentDir = "content/polish"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Strona główna"
languageCode = "pl-PL"
languageName = "PL"
weight = 1

[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2019 [Themefisher](https://themefisher.com) All Rights Reserved"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2

[[Languages.pl.menu.main]]
URL = "about"
name = "O nas"
weight = 1
[[Languages.pl.menu.main]]
URL = "lab"
name = "Lab"
weight = 2
[[Languages.pl.menu.main]]
URL = "contact"
name = "Kontakt"
weight = 3

[[Languages.pl.menu.footer]]
URL = "about"
name = "O nas"
weight = 1
[[Languages.pl.menu.footer]]
URL = "lab"
name = "Lab"
weight = 2
[[Languages.pl.menu.footer]]
URL = "contact"
name = "Kontakt"
weight = 3

[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6

[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6






# [[menu.footer]]
# URL = "project"
# name = "Project"
# weight = 2
# [[menu.footer]]
# URL = "service"
# name = "Service"
# weight = 3
# [[menu.footer]]
# URL = "pricing"
# name = "Pricing"
# weight = 4
# [[menu.footer]]
# URL = "faq"
# name = "FAQ"
# weight = 5
# [[menu.footer]]
# URL = "contact"
# name = "Contact"
# weight = 6

[params]
author = "B. Sikora, J. Źrebiec, A. Piłat"
contact_form_action = "https://getform.io/f/fe7a4709-ea80-4765-ae10-d569261a0a0c"
description = "This is meta description"
email = "demo@email.com"
google_analitycs_id = "UA-166787700-1"
location = "Budynek C3, Aleja Mickiewicza 30, 30-059 Kraków"
logo = "images/logo-1.png"
mobile = "0124857985320"
phone = "+48 12 617 34 84"
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "50.066181"
map_longitude = "19.921567"
map_marker = "images/marker.png"
[params.map]
enable = true
latitude = "50.066181"
longitude = "19.921567"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

[[params.plugins.css]]
link = "css/override_colors.css"
[[params.plugins.css]]
link = "css/main.css"
[[params.plugins.css]]
link = "plugins/fontawesome/css/all.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
# [[params.social]]
# icon = "ion-social-googleplus-outline"
# link = "#"
# [[params.social]]
# icon = "ion-social-linkedin-outline"
# link = "#"
# [[params.social]]
# icon = "ion-social-pinterest-outline"
# link = "#"
# [[params.social]]
# icon = "ion-social-dribbble-outline"
# link = "#"
# [[params.social]]
# icon = "ion-social-twitter-outline"
# link = "#"
# [[params.social]]
# icon = "ion-social-facebook-outline"
# link = "#"
